// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// Generated by mify

package main



import (
	"context"
	books_service_origin "example.com/namespace/oauth-example/go-services/internal/books-service-origin/generated/app"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())

	app_books_service_origin := books_service_origin.NewMifyServiceApp(ctx)
	go func() {
		app_books_service_origin.Run()
		cancel()
	}()

	<-ctx.Done()
}


