openapi: 3.0.0
info:
  contact:
    email: test@mify.io
    name: Maintainer name
  description: This service provides API for accessing and modifying books stored
    in database
  title: books-service
  version: 1.0.0
servers:
- url: <service-url>/
paths:
  /books:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBooksResponse'
          description: OK
      summary: get all books
      tags:
      - /books
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: OK
      summary: create new book
      tags:
      - /books
  /books/{id}:
    get:
      parameters:
      - description: numeric ID of the book to get
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          description: OK
      summary: get book by id
      tags:
      - /books/id
components:
  schemas:
    Book:
      example:
        name: name
        id: 0
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    CreateBookRequest:
      example:
        name: name
      properties:
        name:
          type: string
      required:
      - name
      type: object
    GetBooksResponse:
      example:
        books:
        - name: name
          id: 0
        - name: name
          id: 0
      properties:
        books:
          items:
            $ref: '#/components/schemas/Book'
          type: array
      required:
      - books
      type: object

